### ISSUE TITLE
Infra: Add Hubot to BuildHost

### ISSUE THREAD

**Issue by bryantrobbins** [bryantrobbins/baseball#23]

**Comment by JacobSheppard** [comment]
I'll take a swing at this

![image](https://cloud.githubusercontent.com/assets/6126140/13412572/2ab71dd2-df12-11e5-9846-11ae13ab42ea.png)

**Comment by bryantrobbins** [comment]
Terrible.

**Comment by bryantrobbins** [comment]
@JacobSheppard here's what would need to be done for this:
- Add an ECR repo for the hubot image in baseball/infra/stacks/base.json
- Get a Packer build configuration working for the Hubot container, including steps to push to ECR (see ui/build/\* for some supporting files that can probably be reused here).
- Add a build for the hubot container to baseball/infra/jenkins/build.groovy which calls the necessary packer steps from above
- Add an Nginx config for Hubot to the standard-aws setup on the BuildServer (Puppet code)
- Add a new "hubot.json" and "hubot.properties" to infra/stacks which spec out the ECS Service for the running Hubot container (look at dev.json, dev.properties as an example)
- Add a deploy-HUBOT job to infra/jenkins/build.groovy which deploys the hubot.json cloudformation stack

**Comment by bryantrobbins** [comment]
We might want to add this to standard-aws instead of baseball:
https://github.com/bryantrobbins/standard-aws

That way it could be included in "any side project" made with standard-aws.
