### ISSUE TITLE
UI: Default Use Case Flow

### ISSUE THREAD

**Issue by bryantrobbins** [bryantrobbins/baseball#4]
The Baseball Workbench UI should allow users to describe, execute, and export statistical analysis. To support this goal, there should be a flow of the following activities:
- Select Initial Dataset, from a list of available Public datasets. _For example: Lahman.Hitters_
- Define one or more new columns, in terms of columns from the Initial Dataset and basic arithmetic (add, subtract, multiply, divide). _For example: RC = (H + BB) \* TB / (AB + BB)_
- Define one or more row filters, in terms of column names, values, and comparators, to be applied to the updated data set (Initial + New Columns) prior to export. _For example: Year > 1955_
- Define Exported Artifact, from a list of available export types and their options. _For example: Histogram of RC _
- Click "Generate"
- Receive temporary link to exported files.

The available datasets are:
- Individual tables from the Lahman database (e.g., Hitters, Pitchers, Teams, etc.)
- Retrosheet Gamelogs database (Regular Season, Postseason, or All-Star)

The supported Export Types are:
- Table ordered by X (ASC or DSC)
- Histogram of X
- Scatter Plot of X vs. Y

**Comment by bryantrobbins** [comment]
This is my attempt at some kind of mock-up:

![img_20160227_004722](https://cloud.githubusercontent.com/assets/1299268/13371086/ce443fee-dceb-11e5-8a93-376c2f04ebfd.jpg)

**Comment by mchao47** [comment]
RC = runs created

**Comment by bryantrobbins** [comment]
RC = an example of a stat that someone might want to compute with this tool

**Comment by bryantrobbins** [comment]
Moved this content to a wiki page, as a UI overview:
https://github.com/bryantrobbins/baseball/wiki/UI

Will split out more specific stories for UI features.
